### ISSUE TITLE
Downloaded books are not in *mobi format

### ISSUE THREAD

**Issue by adam-kulagowski** [tp86/legimi#10]
I'm trying to use Your application along w/ Kindle Paperwhite 3. While using Windows client (latest from Legimi web page) ebooks placed on Kindle are in correct *.mobi format (w/ encryption):
```
$ file /media/fidor/Kindle/documents/1018717.azw 
/media/fidor/Kindle/documents/1018717.azw: Mobipocket E-book "Takeshi 3. Pa\305\202ac umar\305\202ych", 1143574 bytes uncompressed, version 6, codepage 65001, encrypted (type 2)
```

However when I'm trying to use Your app, the files I'm getting are in different format (probably native Legimi encryption for Android/Pocketbook - as header look similiar) - which are not recognized by Kindle:
 ```
 $ file 1018717.mobi 
1018717.mobi: data
```

I'm 100% sure I'm using correct device id. I've started comparing `mitmproxy` dumps from the lua app and from Legimi app and there one difference that look interesting. 

Whenever Legimi App is making the request to fetch the book
```
0000000000 11 00 00 00 c8 00 40 00 00 00 5d 8b 0f 00 00 00   ......@...].....
0000000010 00 00 02 00 00 00 00 00 00 00 36 30 30 35 62 37   ..........6005b7
0000000020 34 39 35 64 65 66 34 37 61 32 39 39 61 38 30 37   495def47a299a807
0000000030 38 65 37 64 39 33 64 39 34 66 00 00 ff ff ff ff   8e7d93d94f......
0000000040 ff ff ff ff 01 00 00 00 00 00                     ..........
```
The response from legimi server is:
```
0000000000 11 00 00 00 18 00 e5 08 00 00 00 01 00 00 00 01   ................
0000000010 00 00 00 04 04 00 02 00 08 00 00 00 08 91 16 00   ................
0000000020 00 00 00 00 03 00 3a 00 00 00 00 00 00 08 91 16   ......:.........
0000000030 00 1e 00 00 00 2f 2f 38 2f 2f 65 38 39 37 38 61   .....//8//e8978a
0000000040 39 61 32 65 34 66 65 65 31 63 34 36 38 35 2e 6d   9a2e4fee1c4685.m
0000000050 6f 62 69 10 f2 37 08 1f 03 ed af f0 3b c7 d3 23   obi..7......;..#
0000000060 ea be 7e bd 01 00 19 00 00 00 65 38 39 37 38 61   ..~.......e8978a
0000000070 39 61 32 65 34 66 65 65 31 63 34 36 38 35 2e 6d   9a2e4fee1c4685.m
0000000080 6f 62 69 00 00 56 08 00 00 68 74 74 70 3a 2f 2f   obi..V...http://
0000000090 61 70 70 2e 6c 65 67 69 6d 69 2e 70 6c 2f 73 76   app.legimi.pl/sv
00000000a0 63 2f 73 79 6e 63 2f 6d 6f 62 69 64 6f 77 6e 6c   c/sync/mobidownl
00000000b0 6f 61 64 2e 61 73 70 78 3f 72 3d 65 79 4a 68 62   oad.aspx?r=eyJhb
00000000c0 47 63 69 4f 69 4a 6f 64 48 52 77 4f 69 38 76 64   GciOiJodHRwOi8vd
00000000d0 33 64 33 4c 6e 63 7a 4c 6d 39 79 5a 79 38 79 4d   3d3LnczLm9yZy8yM
```

When using Your script...
```
$ lua legimi download 1018717
```
 the request packet look similar (minus auth. cookie at the end):
```
0000000000 11 00 00 00 c8 00 40 00 00 00 5d 8b 0f 00 00 00   ......@...].....
0000000010 00 00 02 00 00 00 00 00 00 00 36 39 64 32 35 63   ..........69d25c
0000000020 34 61 66 61 65 61 34 64 65 61 62 30 61 64 32 65   4afaea4deab0ad2e
0000000030 37 38 64 32 64 61 33 34 34 65 00 00 ff ff ff ff   78d2da344e......
0000000040 ff ff ff ff 01 00 00 00 00 00                     ..........

```
The response from Legimi points to different URL (`epub` instead of `mobi` and `streameddownload.aspx` instead of `mobidownload.aspx`):
```
0000000000 11 00 00 00 18 00 ae 07 00 00 00 01 00 00 00 01   ................
0000000010 00 00 00 04 04 00 02 00 08 00 00 00 da db 23 00   ..............#.
0000000020 00 00 00 00 03 00 2a 00 00 00 00 00 00 da db 23   ......*........#
0000000030 00 1e 00 00 00 2f 2f 31 2f 2f 65 38 39 37 38 61   .....//1//e8978a
0000000040 39 61 32 65 34 66 65 65 31 63 34 36 38 35 2e 65   9a2e4fee1c4685.e
0000000050 70 75 62 00 01 00 19 00 00 00 65 38 39 37 38 61   pub.......e8978a
0000000060 39 61 32 65 34 66 65 65 31 63 34 36 38 35 2e 65   9a2e4fee1c4685.e
0000000070 70 75 62 00 00 2f 07 00 00 68 74 74 70 3a 2f 2f   pub../...http://
0000000080 61 70 70 2e 6c 65 67 69 6d 69 2e 70 6c 2f 73 76   app.legimi.pl/sv
0000000090 63 2f 73 79 6e 63 2f 73 74 72 65 61 6d 65 64 64   c/sync/streamedd
00000000a0 6f 77 6e 6c 6f 61 64 2e 61 73 70 78 3f 72 3d 65   ownload.aspx?r=e
00000000b0 79 4a 68 62 47 63 69 4f 69 4a 6f 64 48 52 77 4f   yJhbGciOiJodHRwO
00000000c0 69 38 76 64 33 64 33 4c 6e 63 7a 4c 6d 39 79 5a   i8vd3d3LnczLm9yZ
00000000d0 79 38 79 4d 44 41 78 4c 7a 41 30 4c 33 68 74 62   y8yMDAxLzA0L3htb

```

I can attach whole mitmproxy dump on Legimi native app (I was unable to find 1.5.0 version) as well as Yours if You wish (I'll remove password from it) but maybe its a known bug to You.

**Comment by tp86** [comment]
I encountered changing of download urls some time ago and thought it may be useful as ebooks from streameddownload.aspx are downloaded faster.

Also, I haven't used my script for a while, so I may be not aware of changes to protocol. However, fixed version 1.5.0 should work, unless Legimi deprecated it for some reason.

When I have some time in following week, I will try to investigate and fix an issue.

**Comment by tp86** [comment]
Quick update: I attempted to download one book from my list on Android phone using Termux, it looks like it went well (unfortunately, I cannot copy file to Kindle to check if it actually works). Then I tried to download the same book on PC and it disappeared from the list - I cannot also download it using its ID. I can see the book on my shelf via web, however. 

So there's definitely something weird happening, but I don't have much time today to really dig into this.

**Comment by adam-kulagowski** [comment]
I did some digging by myself (no success) but maybe we could replace blindly `streameddownload.aspx` with `mobidownload.aspx` the `r=` parameter looks like JWT token so we might get lucky and i might work.

**Comment by tp86** [comment]
I have an idea, but it will need to wait till tomorrow.

I quickly checked and it seems that providing additional filter for mobi file only to getting book download urls request may help.

**Comment by adam-kulagowski** [comment]
I'm a network guy. Not a programmer (and especially not in lua). I'll just wait for Your solution :)

**Comment by tp86** [comment]
@adam-kulagowski I have prepared PR #11 with fix. Can you use `fix-mobi-download` branch and check if it works for you?

**Comment by adam-kulagowski** [comment]
Works like a charm :D
