### ISSUE TITLE
Error when running deviceId

### ISSUE THREAD

**Issue by jakub-wisniowski** [tp86/legimi#14]
Hi, I get the following error when I run `lua legimi deviceid <device-id>`:

```src/http.lua:2: module 'http.request' not found:
	no field package.preload['http.request']
	no file 'src/http/request.lua'
	no file 'src/http/request/init.lua'
	no file 'lib/http/request/src/http/request.lua'
	no file '.luarocks/share/lua/5.3/http/request.lua'
	no file '/usr/local/share/lua/5.3/http/request.lua'
	no file '/usr/local/share/lua/5.3/http/request/init.lua'
	no file '/usr/local/lib/lua/5.3/http/request.lua'
	no file '/usr/local/lib/lua/5.3/http/request/init.lua'
	no file '/usr/share/lua/5.3/http/request.lua'
	no file '/usr/share/lua/5.3/http/request/init.lua'
	no file './http/request.lua'
	no file './http/request/init.lua'
	no file '.luarocks/lib/lua/5.3/http/request.so'
	no file '/usr/local/lib/lua/5.3/http/request.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/http/request.so'
	no file '/usr/lib/lua/5.3/http/request.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './http/request.so'
	no file '.luarocks/lib/lua/5.3/http.so'
	no file '/usr/local/lib/lua/5.3/http.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/http.so'
	no file '/usr/lib/lua/5.3/http.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './http.so'
```

I installed the dependecies using `luarocks --lua-version 5.3 --tree .luarocks install http` and got info:
``` 
...
http 0.4-0 is now installed in ~/Projects/legimi/.luarocks (license: MIT)
...
```

I never used lua before and have no idea how to debug it (internet is not really helpful), do you know how to fix this? I don't see any `.lua` or `.so` files in the rocks folder.

![Screenshot from 2024-03-02 16-13-26](https://github.com/tp86/legimi/assets/13536711/329d0512-407c-4044-b12a-5f8525ac6bae)
![Screenshot from 2024-03-02 16-12-10](https://github.com/tp86/legimi/assets/13536711/acd1ee1e-db0b-4049-8ed9-6dc7379c03c0)

**Comment by tp86** [comment]
http.so should be under `.luarocks/lib/lua/5.3/http.so`, please check if it exists. Also make sure your Lua version matches one used during installation (5.3 in your case) and that you're running from main repo directory (path above is relative).

If it still doesn't work, let me know, maybe I'll be able to help.

N.B. I have encountered other issues with current version like seeing only few books on the list and not being able to download some books, so I plan to rewrite script in Go, which will hopefully be also easier to install and use.

**Comment by jakub-wisniowski** [comment]
The only files I have in .luarocks/lib/lua/5.3 are: `_cqueues.so`,  `lpeg.so`, ` _openssl.so`. I'm running the command from main repo directory. I use Lua `v5.3.3`

**Comment by tp86** [comment]
I have just checked and http should be actually installed into `.luarocks/share/lua/5.3/http` - it's  Lua source package rather than native one - my mistake. You can double-check if you indeed have something in this directory. I did fresh install and don't have such issue.
