### ISSUE TITLE
Lua on Ubuntu: `unexpected symbol near '<'`

### ISSUE THREAD

**Issue by adam-kulagowski** [tp86/legimi#3]
Hi,

I'm trying to use lua 5.3 on Ubuntu w/ Your scripts and I'm getting this error:

```
lua: legimi.lua:151: unexpected symbol near '<'
```
https://github.com/tp86/legimi/blob/6893ae3666aaa2e43f2768e20827b10f9bc84ab2/src/legimi.lua#L151

Removing `<close>` from that line, moves me forward and gives me well known error regarding token (as You explained in second issue) however I'm curious (as I'm no lua expert) - what am I doing wrong? Unfortunately Google gives no answer here.

**Comment by tp86** [comment]
`<close>` attribute is Lua 5.4 feature.
You can find more information on this (and Lua) [here](http://www.lua.org/manual/5.4/manual.html#3.3.7).

I think in this case it's pretty safe to remove the attribute, or update your Lua version. 

Thank you for pointing this out - script can be easily written to be compatible with older Lua versions that are still being used and popular.

**Comment by tp86** [comment]
Script has been rewritten and should work with Lua 5.3 now.
